version: "3"

services:

  postgres:
      image: postgres:14-alpine
      environment:
          POSTGRES_DB: pwa23
          POSTGRES_USER: usuario
          POSTGRES_PASSWORD: 1234
      volumes:
          - ./data/pgdata:/var/lib/postgresql/data:delegated
      ports:
          - '5432:5432'

  backend:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ./backend/composer/cache:/root/.composer/cache:delegated
      - ./backend/basic:/app:delegated
    environment:
      DDBB_NAME: pwa23
      DDBB_HOST: postgres
      DDBB_PASSWORD: 1234
      PRODUCCION: $PRODUCCION
      PHP_USER_ID: $USERID
    ports:
      - '8000:80'